services:
  app:
    image: enqueue
    build:
      context: .
    working_dir: /application
    volumes:
      - .:/application
    ports:
      - 8090:8090
    environment:
      XDEBUG_MODE: coverage
    networks:
      - dev-default

networks:
  dev-default:
    external: true